name: Feature request
description: Suggest an improvement or new idea
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Suggested solution
    validations:
      required: true
